on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

name: Update cran-to-git packages

jobs:
  update:
    name: Scrape CRAN packages
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: r-universe-org/cran-to-git
      - name: Scrape CRAN descriptions
        uses: r-universe-org/cranscraper@master
        env:
          GITHUB_PAT: ${{ secrets.GHPAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update: 'crantogit'
