on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

name: Update cran-to-git maintainers

jobs:
  update:
    name: Update maintainers.csv
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: r-universe-org/cran-to-git
      - name: Update maintainer csv
        uses: r-universe-org/cranscraper@master
        env:
          GITHUB_PAT: ${{ secrets.GHPAT }}
          GH_APP_ID: ${{ secrets.CRANTOGIT_APP_ID }}
          GH_APP_KEY: ${{ secrets.CRANTOGIT_APP_KEY }}
        with:
          update: 'maintainers'
