on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

name: Trigger all rebuilds

jobs:
  update:
    name: Trigger all rebuilds
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuilds
        uses: r-universe-org/rebuilds@master
        env:
          GITHUB_PAT: ${{ secrets.GHPAT }}
          CRANLIKEPWD: ${{ secrets.CRANLIKEPWD }}
          SCHEDULE: "NIGHTLY"
