on:
  workflow_dispatch:
    inputs:
      update_all_workflows:
        description: Force updating workflow files
        required: false
#  schedule:
#    - cron: '*/60 * * * *'

name: Sync all universes

jobs:
  update:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - name: Sync all universes
        uses: r-universe-org/sync@master
        with:
          monorepo_url: 'all'
          update_all_workflows: ${{ github.event.inputs.update_all_workflows }}
        env:
          GITHUB_PAT: ${{ secrets.GHPAT }}
